name: save_points_pdf_templates_example
description: Example app for save_points_pdf_templates.
publish_to: 'none'

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  save_points_pdf_templates:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Tajawal/Tajawal-Regular.ttf
    - assets/fonts/Tajawal/Tajawal-Bold.ttf
    - assets/fonts/Tajawal/Tajawal-Regular.ttf
    - assets/fonts/Tajawal/Tajawal-Bold.ttf
